### ISSUE TITLE
error while trying

### ISSUE THREAD

**Issue by gupadhyaya** [vinhbhn/harmony_truffle_hdwallet#1]
I wanted to evaluate your solution, however hitting the same error. I was wondering if there is any configuration that I am missing?
```
Error: Error: Error: while migrating Migrations: blockchain chain id:2, given 0: invalid chain id for signer
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:96:1)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:99:1)
Truffle v5.0.38 (core: 5.0.38)
Node v15.14.0
```

**Comment by vinhbhn** [comment]
I tested the migrate okay with truffe v5.3 and nodejs v12.22 (or v10.21). And I also tested with legacy interface and this okay.

**Comment by vinhbhn** [comment]
The truffle v5.1 using method eth_call 
```
Starting migrations...
======================
> Network name:    'testnet'
> Network id:      1666700000
> Block gas limit: 80000000 (0x4c4b400)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_call",
   >   "params": [
   >     {
   >       "from": "0xc42ec4d9cd53621d6925d67970df07878928c007",
   >       "gas": "0x6691b7",
   >       "gasPrice": "0x4a817c800",
   >       "data": "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061019c806100606000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063445df0ac146100465780638da5cb5b14610064578063fdacd576146100ae575b600080fd5b61004e6100dc565b6040518082815260200191505060405180910390f35b61006c6100e2565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6100da600480360360208110156100c457600080fd5b8101908080359060200190929190505050610107565b005b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561016457806001819055505b5056fea265627a7a72315820aa0d2624d8d84d1ea9dedc902cc299cce4408d6daaa8909e8dc87f40b4ac70b564736f6c63430005100032"
   >     },
   >     "latest"
   >   ],
   >   "id": 1618378292183
   > }
 <   {
 <     "id": 1618378292183,
 <     "jsonrpc": "2.0",
 <     "result": "0x608060405234801561001057600080fd5b50600436106100415760003560e01c8063445df0ac146100465780638da5cb5b14610064578063fdacd576146100ae575b600080fd5b61004e6100dc565b6040518082815260200191505060405180910390f35b61006c6100e2565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6100da600480360360208110156100c457600080fd5b8101908080359060200190929190505050610107565b005b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561016457806001819055505b5056fea265627a7a72315820aa0d2624d8d84d1ea9dedc902cc299cce4408d6daaa8909e8dc87f40b4ac70b564736f6c63430005100032"
 <   }

Error:  *** Deployment Failed ***

"Migrations" -- blockchain chain id:2, given 0: invalid chain id for signer.
``` 
while truffle v5.3 using method evm_snapshot
```
Contract: MetaCoin
   > {
   >   "jsonrpc": "2.0",
   >   "method": "evm_snapshot",
   >   "id": 1618379519459
   > }
```

**Comment by gupadhyaya** [comment]
thanks. the bug was in the truffle version 5.0.38. I upgraded to 5.3 and it works now. thanks.

**Comment by billtlee** [comment]
I am running into this exact problem with truffle 5.4.22

`Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'harmonytest'
> Network id:      1666700000
> Block gas limit: 80000000 (0x4c4b400)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- blockchain chain id:2, given 0: invalid chain id for signer.

    at /Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.22 (core: 5.4.22)
Node v16.0.0`

**Comment by dipesh517** [comment]
> I am running into this exact problem with truffle 5.4.22
> 
> # `Compiling your contracts...
> > Everything is up to date, there is nothing to compile.
> 
> # Starting migrations...
> > Network name:    'harmonytest'
> > Network id:      1666700000
> > Block gas limit: 80000000 (0x4c4b400)
> 
> # 1_initial_migration.js
> ## Deploying 'Migrations'
> Error: *** Deployment Failed ***
> 
> "Migrations" -- blockchain chain id:2, given 0: invalid chain id for signer.
> 
> ```
> at /Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at Migration._deploy (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
> at Migration._load (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
> at Migration.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
> at Object.runMigrations (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
> at Object.runFrom (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
> at Object.runAll (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
> at Object.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
> at runMigrations (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
> at Object.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
> at Command.run (/Users/bill/Documents/MyProjects/NFTSDao/tribute-contracts/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
> ```
> 
> Truffle v5.4.22 (core: 5.4.22) Node v16.0.0`



> 

I am also facing the same issue. Did you find any solution

**Comment by billtlee** [comment]
I ran into this problem on my mac.  I got around it by using a docker image dev container using linux.  Maybe its something with the mac...  Hope that helps.
